# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f4ce46b8c539951a87c624f20a7bef55841d1225bab9fcb27417bb2e41c56e6c60a4504ff85ce6a20a0583475560f5faa92206b3962ba0ce86e578d89f98c4

test:
  secret_key_base: f6af83b78fd9364cb96afb9dc2c9a5eab5901f30961d95000b69a2396d2961dea41f884390a12f01517450078723cf99dde48d343cc16b4cafc2e8d4c882d3b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
